shell /usr/bin/zsh

confirm_os_window_close 0
allow_remote_control yes

font_family      CaskaydiaMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

cursor_shape underline
shell_integration no-cursor
cursor_trail 1
cursor_trail_decay 0.1 0.2
# url_color #0087bd
url_style dotted
show_hyperlink_targets no
underline_hyperlinks always
enabled_layouts tall,*
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_activity_symbol >

background_opacity 0.95
window_border_width 2pt
single_window_margin 0



# BEGIN_KITTY_THEME
include ~/.cache/wallust/kitty.conf
# END_KITTY_THEME
