general {
    ignore_dbus_inhibit = false
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session && sleep 3
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 120
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

listener {
    timeout = 180
    on-timeout = sleep 0.5 && ~/.config/binc/screensaver
}

listener {
    timeout = 600
    on-timeout = hyprlock
}

listener {
    timeout = 780
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 5. Спящий режим (1200с / 20min)
listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
