-- Generated by nwg-displays on 2026-09-13 at 14:22:01. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@60.0",
    position = "2487x464",
    scale = 2.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@143.98",
    position = "439x212",
    scale = 1.25
})
