-- Generated by nwg-displays on 2026-10-04 at 17:42:09. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@60.0",
    position = "3590x559",
    scale = 2.0
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@74.97",
    position = "462x175",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@143.98",
    position = "1542x307",
    scale = 1.25
})
