-- Generated by nwg-displays on 2026-08-02 at 16:01:24. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@60.0",
    position = "0x90",
    scale = 2.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "1440x0",
    scale = 1.0
})
