plugin {
    hyprexpo {
        columns = 3
        gap_size = 1
        bg_col = rgb(ffffff)
        workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1
        hyprexpo-gesture = 3, vertical, expo
    }
    split-monitor-workspaces {
        count = 9                     # Количество столов на каждом мониторе
        keep_focused = 1               # Не терять фокус при перезагрузке
        enable_persistent_workspaces = 1 # (Опционально) Не создавать столы заранее
        enable_notifications = 0       # Отключить уведомления плагина
    }
    hyprtasking {
        layout = grid
        gap_size = 0
        border_size = 0
        bg_color = 0xee111111

        select_button = 273
        drag_button = 272

        exit_on_hovered = false

        gestures {
            enabled = true
            open_fingers = 3
        }

    }
}
