###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = ~/.config/rofi/launchers/type-2/launcher.sh
$appMenu = ~/.config/rofi/applets/bin/apps.sh
$powermenu = ~/.config/rofi/powermenu/type-1/powermenu.sh
$browser = chromium --ozone-platform=wayland --enable-features=TouchpadOverscrollHistoryNavigation
$bufferman = [float; size 900 550; center] kitty -e clipse
$screenshot = grim - | tee /tmp/temp_screenshot.png && hyprctl dispatch exec "[float; size 1300 750; center] eog /tmp/temp_screenshot.png"
$touchpadToggle = ~/.config/binc/touchpad_toggle
