##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule = suppress_event maximize, match:class *


# Fix some dragging issues with XWayland
windowrule = no_focus match:class ^$,match:title ^$,match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0
windowrule {
    name = dragging_fix
    match:class = ^$
    match:title = ^$
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
}

windowrule {
    name = screensaver
    match:class = arch.screensaver
    fullscreen = 1
}

windowrule {
    name = previewer
    match:class = org.gnome.NautilusPreviewer
    float = 1
    size = 800 600
}

windowrule {
    name = vpn
    match:class = Windscribe
    float = 1
    size = 350 284
}

windowrule {
    name = calculator
    match:class = org.gnome.Calculator
    float = 1
}

windowrule {
    name = chromium_scroll
    match:class = chromium
    scroll_touchpad = 0.1
}
