##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule = suppress_event maximize, match:class *


# Fix some dragging issues with XWayland
windowrule = no_focus match:class ^$,match:title ^$,match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0

# Используем новый синтаксис без v2 (хотя v2 всё еще алиас)
windowrule = fullscreen ^(arch.screensaver)$
