#!/usr/bin/env bash

WALLPAPER="$1"

if [ -z "$WALLPAPER" ]; then
  echo "Использование: ./script.sh /путь/к/обоям"
  exit 1
fi

CURRENT_WALL="$HOME/Wallpapers/current.jpg"

cp -f "$WALLPAPER" "$CURRENT_WALL"

swww img "$CURRENT_WALL" --transition-type any

wallust run "$CURRENT_WALL"

hyprctl reload
killall -SIGUSR2 waybar
killall -USR1 kitty
swaync-client -rs && swaync-client -t -sw && swaync-client -t

echo "Theme updated! Image saved to $CURRENT_WALL"
