foreground            #e9e0e5
background            #161216
selection_foreground  #47214e
selection_background  #e8b6ed
url_color             #bece83
cursor                #e8b6ed
cursor_text_color     #47214e

color0   #161216
color1   #ffb4ab
color2   #e8b6ed
color3   #bece83
color4   #e8b6ed
color5   #bece83
color6   #687635
color7   #e9e0e5

color8   #998d97
color9   #ffb4ab
color10  #e8b6ed
color11  #bece83
color12  #e8b6ed
color13  #bece83
color14  #687635
color15  #e9e0e5

tab_bar_background              #161216
tab_bar_margin_color            #161216
active_tab_foreground           #47214e
active_tab_background           #e8b6ed
inactive_tab_foreground         #d0c3cd
inactive_tab_background         #161216
